name: FastAPI + Github Actions + AWS

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.6
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: Format code
      run: |
        make format
  
